# Generated by Django 3.1.4 on 2020-12-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_auto_20201220_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall_color',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
