# Generated by Django 3.1.4 on 2020-12-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_auto_20201223_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall_color',
            field=models.CharField(max_length=120),
        ),
    ]
