# Generated by Django 3.1.4 on 2020-12-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('cinema_app', '0004_auto_20201225_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('updated', models.DateField(auto_now=True)),
            ],
            bases=('authtoken.token',),
        ),
    ]
