# Generated by Django 3.1.4 on 2020-12-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0005_cinematoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CinemaToken',
        ),
    ]
